apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s-persistence-lab
  region: us-east-1

iam:
  withOIDC: true

addons:
  - name: aws-ebs-csi-driver
    wellKnownPolicies:
      ebsCSIController: true

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      allow: false